/* Generated by Frama-C */
#include "stdio.h"
#include "stdlib.h"
int main(void)
{
  int __retres;
  __e_acsl_memory_init((int *)0,(char ***)0,(size_t)8);
  char *a = malloc((unsigned long)7);
  __retres = 0;
  __e_acsl_memory_clean();
  return __retres;
}


