/* Generated by Frama-C */
#include "stdio.h"
#include "stdlib.h"
int main(void)
{
  int __retres;
  __e_acsl_memory_init((int *)0,(char ***)0,(size_t)8);
  int x = 0;
  if (x) 
    /*@ assert \false; */
    __e_acsl_assert(0,(char *)"Assertion",(char *)"main",(char *)"\\false",6);
  __retres = 0;
  return __retres;
}


