(* This file is generated by Makefile. Do not modify. *)
let version = "Beryllium-20090902"
let date = "Wed Sep 23 17:37:52 CEST 2009"
let is_gui = ref false
let datadir = try Sys.getenv "FRAMAC_SHARE" with Not_found -> "/usr/local/share/frama-c"
let libdir = try Sys.getenv "FRAMAC_LIB" with Not_found -> "/usr/local/lib/frama-c"
let plugin_dir = try Sys.getenv "FRAMAC_PLUGIN" with Not_found -> try (Sys.getenv "FRAMAC_LIB") ^ "/plugins" with Not_found -> "/usr/local/lib/frama-c/plugins"
let static_plugins = [ "Occurrence"; "Metrics"; "Syntactic_callgraph"; "Value"; "From"; "Users"; "Constant_Propagation"; "Postdominators"; "Inout"; "Semantic_callgraph"; "Wp"; "Security"; "Impact"; "Pdg"; "Scope"; "Sparecode"; "Slicing" ]
let static_gui_plugins = [ "Occurrence"; "Metrics"; "Syntactic_callgraph"; "Value"; "From"; "Wp"; "Security"; "Impact"; "Scope"; "Slicing" ]
