#!/bin/sh

# benchmark for jessie
export JESSIELIB=`pwd`/../../lib
export WHYCOQ=`pwd`/../../lib/coq
make="make WHYCOQ=$WHYCOQ"

echo "JC parsing/typing (bad)"
cd bad
parsing="../../../bin/jessie.opt -type-only"
for f in *.jc; do
    echo -n "  "$f"... "
    if $parsing  $f > /dev/null 2>&1; then
	echo "jessie FAILED (accepted a bad file)"
	$parsing $f
	exit 1
    else
	echo "jessie ok... "
    fi
done

echo "JC interp (good)"
cd ../good

bench_jc_good () {
    options="$* -why-opt -split-user-conj -why-opt -show-time"
    echo "-------------------------------------------------------------------"
    echo "Bench Jessie+Simplify/Yices/Ergo with options: $options"
    parsing="../../../bin/jessie.opt $options"

    rm -f why/*.why
    rm -f simplify/*_why.sx
    rm -f smtlib/*_why.smt
    VCS=""
    for file in *.jc; do
	echo -n "  Generating VCs for $file... "
	f=`basename $file .jc`
	if $parsing  $f.jc > /tmp/jessie.tmp 2>&1; then
	    if $make -f $f.makefile simplify/${f}_why.sx > /tmp/jessie.tmp 2>&1 ; then
		if $make -f $f.makefile smtlib/${f}_why.smt > /tmp/jessie.tmp 2>&1 ; then
		    if $make -f $f.makefile why/${f}_why.why > /tmp/jessie.tmp 2>&1 ; then
			VCS="$VCS simplify/${f}_why.sx smtlib/${f}_why.smt why/${f}_why.why"    
			echo "ok"
		    else
			echo "why FAILED :"
			cat /tmp/jessie.tmp
			exit 1
		    fi
		else
		    echo "why FAILED :"
		    cat /tmp/jessie.tmp
		    exit 1
		fi
	    else
		echo "why FAILED :"
		cat /tmp/jessie.tmp
		exit 1
	    fi
	else
	    echo "jessie FAILED (rejected a good file) :"
	    cat /tmp/jessie.tmp
	    exit 1
	fi
    done
    ../../../bin/dp.opt -timeout 10 $VCS 2>/dev/null || true
}

bench_jc_good
# bench_jc_good -separation -no-zone-type

# Coq proofs
# for f in $FILES; do
#     echo -n "  $f.c... "
#     rm -f coq/jessie_spec_why.v
#     if $parsing  $f.c > /tmp/jessie.tmp 2>&1; then
# 	echo -n "jessie ok... "
# 	if $make -f $f.makefile coq > /tmp/jessie.tmp 2>&1; then
# 	    n=`grep -c Admitted coq/${f}_why.v`
# 	    if test $n -ne 0 ; then
# 		echo "Coq proof ok (with $n Admitted)... "
# 	    else
# 		echo "Coq proof ok... "
# 	    fi
# 	else
# 	    echo "Coq proof FAILED !"
# 	    cat /tmp/jessie.tmp
# 	    exit 1
# 	fi
#     else
# 	echo "jessie FAILED (rejected a good file) :"
# 	cat /tmp/jessie.tmp
# 	exit 1
#     fi
# done


