(* This file was originally generated by why.
   It can be modified; only the generated parts will be overwritten. *)

Require Import Why.

Parameter F : Z -> Z.
Axiom F_0 : F 0 = 1%Z.
Axiom F_1 : F 1 = 1%Z.
Axiom F_n : forall n:Z, (n >= 2)%Z -> F n = (F (n - 1) + F (n - 2))%Z.
Hint Resolve F_0 F_1 F_n .

Proof.
intuition.
assert (n=0 \/ n=1). omega. intuition; subst; auto.
Save.

Proof.
intuition.
Save.

Proof.
intuition.
Save.

Proof.
intuition.
Save.

Proof.
intuition.
Save.

Proof.
intuition.
subst; symmetry; auto with *.
Save.


Proof.
intuition.
subst; auto.
Save.

Proof.
intuition.
Save.

Proof.
intuition.
subst; symmetry.
cut (1 <= x).
 replace x with (x + 1 - 1)%Z.
 generalize (x + 1)%Z.
intros; ring (z - 1 + 1)%Z; replace (z - 1 - 1)%Z with (z - 2)%Z.
 auto with *.
omega.
omega.
assumption.
subst; ring (x + 1 - 1)%Z; trivial.
Save.


Proof.
intuition.
assert (n=0 \/ n=1). omega. intuition; subst; auto.
Save.

Proof.
intuition.
Save.


Proof.
intuition.
Save.

Proof.
intuition.
subst; symmetry.
cut (1 <= k).
 replace k with (k + 1 - 1)%Z.
 generalize (k + 1)%Z.
intros; ring (z - 1 + 1)%Z; replace (z - 1 - 1)%Z with (z - 2)%Z.
 auto with *.
omega.
omega.
assumption.
subst; ring (k + 1 - 1)%Z; trivial.
Save.

Proof.
intuition.
subst.
assert (k=n). omega. subst; auto.
Save.

Proof.
intuition.
assert (n=0 \/ n=1). omega. intuition; subst; auto.
Save.


Proof.
intuition.
assert (n=0 \/ n=1). omega. intuition; subst; auto.
Save.

Proof.
intuition.
Save.

Proof.
intuition; ArraySubst t0.
Save.

Proof.
intuition.
subst; repeat rewrite array_length_update; trivial.
subst. assert (i=0 \/ i=1). omega. intuition; subst.
AccessOther; auto with *.
AccessSame; auto with *.
Save.

Proof.
intuition.
Save.

Proof.
intuition.
Save.

Proof.
intuition.
Save.

Proof.
intuition; subst.
repeat rewrite array_length_update; assumption.
assert (i<k \/ i=k). omega. intuition; subst.
AccessOther; auto.
AccessSame.
replace (access t2 (k-1)) with (F (k-1)); symmetry; auto with *.
replace (access t2 (k-2)) with (F (k-2)); symmetry; auto with *.
symmetry; auto with *.
Save.

Proof.
intuition.
Save.

Proof.
intuition; subst; intuition.
Save.


(*Why logic*) Definition F : Z -> Z.
Admitted.

(*Why axiom*) Lemma F_0 : (F 0) = 1.
Admitted.

(*Why axiom*) Lemma F_1 : (F 1) = 1.
Admitted.

(*Why axiom*) Lemma F_n :
  (forall (n:Z), (n >= 2 -> (F n) = ((F (n - 1)) + (F (n - 2))))).
Admitted.

