(* This file was originally generated by why.
   It can be modified; only the generated parts will be overwritten. *)

Require Import Why.


Proof.
intuition.
Save.

Proof.
intuition.
Save.

Proof.
intuition.
Save.

Proof.
intuition.
assert (k=i \/ k<i). omega. 
intuition; subst; eauto. 
Save.

Proof.
intuition.
subst.
apply H2 with k; auto with *.
Save.

Proof.
intuition.
Save.

Proof.
intuition.
Save.

Proof.
intuition.
Save.

Proof.
intuition.
assert (k=i \/ k<i). omega.
intuition; subst; eauto.
Save.

Proof.
intuition.
subst.
apply H2 with k; auto with *.
Save.

Proof.
intuition.
Save.

Proof.
intuition.
Save.

Proof.
intuition.
Save.

Proof.
intuition.
Save.

Proof.
intuition.
Save.

Proof.
intuition.
assert( k=i \/ i+1<=k). omega.
intuition; subst; auto with *.
eauto.
Save.
Proof.
(* FILL PROOF HERE *)
Save.

Proof.
(* FILL PROOF HERE *)
Save.

