(* This file was originally generated by why.
   It can be modified; only the generated parts will be overwritten. *)

Require Export Caduceus.

(*Why type*) Definition global: Set.
Admitted.







(*Why predicate*) Definition purse_inv  (balance_global:(memory Z global)) (alloc:alloc_table) (p:(pointer global))
  := (* CADUCEUS_1 *) ((valid alloc p) /\ (acc balance_global p) >= 0).

