/* Generated by Frama-C */
typedef unsigned long size_t;
struct __e_acsl_mpz_struct {
   int _mp_alloc ;
   int _mp_size ;
   unsigned long *_mp_d ;
};
typedef struct __e_acsl_mpz_struct __e_acsl_mpz_struct;
typedef __e_acsl_mpz_struct ( __attribute__((__FC_BUILTIN__)) __e_acsl_mpz_t)[1];
struct __e_acsl_mpq_struct {
   __e_acsl_mpz_struct _mp_num ;
   __e_acsl_mpz_struct _mp_den ;
};
typedef struct __e_acsl_mpq_struct __e_acsl_mpq_struct;
typedef __e_acsl_mpq_struct ( __attribute__((__FC_BUILTIN__)) __e_acsl_mpq_t)[1];
typedef struct _IO_FILE FILE;
/*@ ghost extern int __e_acsl_init; */

extern size_t __e_acsl_heap_allocation_size;

typedef unsigned short __uint16_t;
typedef unsigned int __uint32_t;
typedef unsigned long __uint64_t;
typedef long __off_t;
typedef long __off64_t;
struct _IO_FILE;
typedef void _IO_lock_t;
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[((unsigned long)15 * sizeof(int) - (unsigned long)4 * sizeof(void *)) - sizeof(size_t)] ;
};
/* compiler builtin: 
   unsigned int __builtin_bswap32(unsigned int);   */
/* compiler builtin: 
   unsigned long __builtin_bswap64(unsigned long);   */
__inline static unsigned int __bswap_32(unsigned int __bsx)
{
  unsigned int tmp;
  tmp = __builtin_bswap32(__bsx);
  return tmp;
}

__inline static __uint64_t __bswap_64(__uint64_t __bsx)
{
  __uint64_t tmp;
  tmp = __builtin_bswap64(__bsx);
  return tmp;
}

__inline static __uint16_t __uint16_identity(__uint16_t __x)
{
  return __x;
}

__inline static __uint32_t __uint32_identity(__uint32_t __x)
{
  return __x;
}

__inline static __uint64_t __uint64_identity(__uint64_t __x)
{
  return __x;
}

/*@
predicate diffSize{L1, L2}(ℤ i) =
  \at(__e_acsl_heap_allocation_size,L1) -
  \at(__e_acsl_heap_allocation_size,L2) ≡ i;

*/
extern  __attribute__((__FC_BUILTIN__)) int ( /* missing proto */ __e_acsl_memory_init)(
int *x_0, char ***x_1, unsigned long x_2);

extern  __attribute__((__FC_BUILTIN__)) int ( /* missing proto */ __e_acsl_store_block)(
void *x_0, unsigned long x_1);

extern  __attribute__((__FC_BUILTIN__)) int ( /* missing proto */ __e_acsl_full_init)(
void *x_0);

extern  __attribute__((__FC_BUILTIN__)) int ( /* missing proto */ __e_acsl_delete_block)(
void *x_0);

extern  __attribute__((__FC_BUILTIN__)) int ( /* missing proto */ __e_acsl_memory_clean)(
void);

int main(int argc, char **argv)
{
  int __retres;
  __e_acsl_memory_init(& argc,& argv,8UL);
  __e_acsl_memory_init(& argc,& argv,8UL);
  __e_acsl_store_block((void *)(& argc),4UL);
  {
    int *p;
    __e_acsl_store_block((void *)(& p),8UL);
    __e_acsl_store_block((void *)(& p),8UL);
    switch (argc) {
      default: ;
      __e_acsl_full_init((void *)(& p));
      __e_acsl_full_init((void *)(& p));
      p = & argc;
      break;
    }
    __e_acsl_delete_block((void *)(& p));
    __e_acsl_delete_block((void *)(& p));
  }
  __retres = 0;
  __e_acsl_delete_block((void *)(& argc));
  __e_acsl_memory_clean();
  __e_acsl_delete_block((void *)(& argc));
  __e_acsl_memory_clean();
  return __retres;
}


