/* Generated by Frama-C */
int main(void)
{
  int __retres;
  long x;
  int y;
  x = (long)0;
  y = 0;
  /*@ assert (int)x ≡ y; */
  {
    mpz_t __gen_e_acsl_x;
    unsigned long __gen_e_acsl_cast;
    mpz_t __gen_e_acsl_;
    mpz_t __gen_e_acsl_y;
    int __gen_e_acsl_eq;
    __gmpz_init_set_si(__gen_e_acsl_x,x);
    __gen_e_acsl_cast = __gmpz_get_ui((__mpz_struct const *)(__gen_e_acsl_x));
    __gmpz_init_set_ui(__gen_e_acsl_,__gen_e_acsl_cast);
    __gmpz_init_set_si(__gen_e_acsl_y,(long)y);
    __gen_e_acsl_eq = __gmpz_cmp((__mpz_struct const *)(__gen_e_acsl_),
                                 (__mpz_struct const *)(__gen_e_acsl_y));
    __e_acsl_assert(__gen_e_acsl_eq == 0,(char *)"Assertion",(char *)"main",
                    (char *)"(int)x == y",10);
    __gmpz_clear(__gen_e_acsl_x);
    __gmpz_clear(__gen_e_acsl_);
    __gmpz_clear(__gen_e_acsl_y);
  }
  /*@ assert x ≡ (long)y; */
  {
    mpz_t __gen_e_acsl_x_2;
    mpz_t __gen_e_acsl_y_2;
    unsigned long __gen_e_acsl_cast_2;
    mpz_t __gen_e_acsl__2;
    int __gen_e_acsl_eq_2;
    __gmpz_init_set_si(__gen_e_acsl_x_2,x);
    __gmpz_init_set_si(__gen_e_acsl_y_2,(long)y);
    __gen_e_acsl_cast_2 = __gmpz_get_ui((__mpz_struct const *)(__gen_e_acsl_y_2));
    __gmpz_init_set_ui(__gen_e_acsl__2,__gen_e_acsl_cast_2);
    __gen_e_acsl_eq_2 = __gmpz_cmp((__mpz_struct const *)(__gen_e_acsl_x_2),
                                   (__mpz_struct const *)(__gen_e_acsl__2));
    __e_acsl_assert(__gen_e_acsl_eq_2 == 0,(char *)"Assertion",
                    (char *)"main",(char *)"x == (long)y",11);
    __gmpz_clear(__gen_e_acsl_x_2);
    __gmpz_clear(__gen_e_acsl_y_2);
    __gmpz_clear(__gen_e_acsl__2);
  }
  /*@ assert y ≡ (int)0; */
  {
    mpz_t __gen_e_acsl_y_3;
    mpz_t __gen_e_acsl__3;
    unsigned long __gen_e_acsl_cast_3;
    mpz_t __gen_e_acsl__4;
    int __gen_e_acsl_eq_3;
    __gmpz_init_set_si(__gen_e_acsl_y_3,(long)y);
    __gmpz_init_set_si(__gen_e_acsl__3,0L);
    __gen_e_acsl_cast_3 = __gmpz_get_ui((__mpz_struct const *)(__gen_e_acsl__3));
    __gmpz_init_set_ui(__gen_e_acsl__4,__gen_e_acsl_cast_3);
    __gen_e_acsl_eq_3 = __gmpz_cmp((__mpz_struct const *)(__gen_e_acsl_y_3),
                                   (__mpz_struct const *)(__gen_e_acsl__4));
    __e_acsl_assert(__gen_e_acsl_eq_3 == 0,(char *)"Assertion",
                    (char *)"main",(char *)"y == (int)0",13);
    __gmpz_clear(__gen_e_acsl_y_3);
    __gmpz_clear(__gen_e_acsl__3);
    __gmpz_clear(__gen_e_acsl__4);
  }
  /*@ assert (unsigned int)y ≡ (unsigned int)0; */
  {
    mpz_t __gen_e_acsl_y_4;
    unsigned long __gen_e_acsl_cast_4;
    mpz_t __gen_e_acsl__5;
    mpz_t __gen_e_acsl__6;
    unsigned long __gen_e_acsl_cast_5;
    mpz_t __gen_e_acsl__7;
    int __gen_e_acsl_eq_4;
    __gmpz_init_set_si(__gen_e_acsl_y_4,(long)y);
    __gen_e_acsl_cast_4 = __gmpz_get_ui((__mpz_struct const *)(__gen_e_acsl_y_4));
    __gmpz_init_set_ui(__gen_e_acsl__5,__gen_e_acsl_cast_4);
    __gmpz_init_set_si(__gen_e_acsl__6,0L);
    __gen_e_acsl_cast_5 = __gmpz_get_ui((__mpz_struct const *)(__gen_e_acsl__6));
    __gmpz_init_set_ui(__gen_e_acsl__7,__gen_e_acsl_cast_5);
    __gen_e_acsl_eq_4 = __gmpz_cmp((__mpz_struct const *)(__gen_e_acsl__5),
                                   (__mpz_struct const *)(__gen_e_acsl__7));
    __e_acsl_assert(__gen_e_acsl_eq_4 == 0,(char *)"Assertion",
                    (char *)"main",
                    (char *)"(unsigned int)y == (unsigned int)0",14);
    __gmpz_clear(__gen_e_acsl_y_4);
    __gmpz_clear(__gen_e_acsl__5);
    __gmpz_clear(__gen_e_acsl__6);
    __gmpz_clear(__gen_e_acsl__7);
  }
  /*@ assert y ≢ (int)0xfffffffffffffff; */
  {
    mpz_t __gen_e_acsl_y_5;
    mpz_t __gen_e_acsl__8;
    unsigned long __gen_e_acsl_cast_6;
    mpz_t __gen_e_acsl__9;
    int __gen_e_acsl_ne;
    __gmpz_init_set_si(__gen_e_acsl_y_5,(long)y);
    __gmpz_init_set_ui(__gen_e_acsl__8,1152921504606846975UL);
    __gen_e_acsl_cast_6 = __gmpz_get_ui((__mpz_struct const *)(__gen_e_acsl__8));
    __gmpz_init_set_ui(__gen_e_acsl__9,__gen_e_acsl_cast_6);
    __gen_e_acsl_ne = __gmpz_cmp((__mpz_struct const *)(__gen_e_acsl_y_5),
                                 (__mpz_struct const *)(__gen_e_acsl__9));
    __e_acsl_assert(__gen_e_acsl_ne != 0,(char *)"Assertion",(char *)"main",
                    (char *)"y != (int)0xfffffffffffffff",17);
    __gmpz_clear(__gen_e_acsl_y_5);
    __gmpz_clear(__gen_e_acsl__8);
    __gmpz_clear(__gen_e_acsl__9);
  }
  /*@ assert (unsigned int)y ≢ (unsigned int)0xfffffffffffffff; */
  {
    mpz_t __gen_e_acsl_y_6;
    unsigned long __gen_e_acsl_cast_7;
    mpz_t __gen_e_acsl__10;
    mpz_t __gen_e_acsl__11;
    unsigned long __gen_e_acsl_cast_8;
    mpz_t __gen_e_acsl__12;
    int __gen_e_acsl_ne_2;
    __gmpz_init_set_si(__gen_e_acsl_y_6,(long)y);
    __gen_e_acsl_cast_7 = __gmpz_get_ui((__mpz_struct const *)(__gen_e_acsl_y_6));
    __gmpz_init_set_ui(__gen_e_acsl__10,__gen_e_acsl_cast_7);
    __gmpz_init_set_ui(__gen_e_acsl__11,1152921504606846975UL);
    __gen_e_acsl_cast_8 = __gmpz_get_ui((__mpz_struct const *)(__gen_e_acsl__11));
    __gmpz_init_set_ui(__gen_e_acsl__12,__gen_e_acsl_cast_8);
    __gen_e_acsl_ne_2 = __gmpz_cmp((__mpz_struct const *)(__gen_e_acsl__10),
                                   (__mpz_struct const *)(__gen_e_acsl__12));
    __e_acsl_assert(__gen_e_acsl_ne_2 != 0,(char *)"Assertion",
                    (char *)"main",
                    (char *)"(unsigned int)y != (unsigned int)0xfffffffffffffff",
                    18);
    __gmpz_clear(__gen_e_acsl_y_6);
    __gmpz_clear(__gen_e_acsl__10);
    __gmpz_clear(__gen_e_acsl__11);
    __gmpz_clear(__gen_e_acsl__12);
  }
  __retres = 0;
  return __retres;
}


