/* Generated by Frama-C */
#include "stdio.h"
#include "stdlib.h"
struct __anonstruct_r_1 {
   int x ;
   int y ;
};
union __anonunion_s_2 {
   int x ;
   char *y ;
};
int main(void)
{
  int __retres;
  union __anonunion_s_2 s;
  __e_acsl_memory_init((int *)0,(char ***)0,(size_t)8);
  int n = -2;
  /*@ assert \let u = n * n; u ≥ 0; */
  {
    __e_acsl_mpz_t __gen_e_acsl_u;
    __e_acsl_mpz_t __gen_e_acsl_n;
    __e_acsl_mpz_t __gen_e_acsl_mul;
    __e_acsl_mpz_t __gen_e_acsl_;
    int __gen_e_acsl_ge;
    __gmpz_init_set_si(__gen_e_acsl_n,(long)n);
    __gmpz_init(__gen_e_acsl_mul);
    __gmpz_mul(__gen_e_acsl_mul,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n));
    __gmpz_init_set(__gen_e_acsl_u,
                    (__e_acsl_mpz_struct const *)(__gen_e_acsl_mul));
    __gmpz_init_set_si(__gen_e_acsl_,0L);
    __gen_e_acsl_ge = __gmpz_cmp((__e_acsl_mpz_struct const *)(__gen_e_acsl_u),
                                 (__e_acsl_mpz_struct const *)(__gen_e_acsl_));
    __e_acsl_assert(__gen_e_acsl_ge >= 0,(char *)"Assertion",(char *)"main",
                    (char *)"\\let u = n * n; u >= 0",7);
    __gmpz_clear(__gen_e_acsl_u);
    __gmpz_clear(__gen_e_acsl_n);
    __gmpz_clear(__gen_e_acsl_mul);
    __gmpz_clear(__gen_e_acsl_);
  }
  /*@ assert \let u = n * n; \let v = u + 1; u > 0; */
  {
    __e_acsl_mpz_t __gen_e_acsl_u_2;
    __e_acsl_mpz_t __gen_e_acsl_n_2;
    __e_acsl_mpz_t __gen_e_acsl_mul_2;
    __e_acsl_mpz_t __gen_e_acsl_v;
    __e_acsl_mpz_t __gen_e_acsl__2;
    __e_acsl_mpz_t __gen_e_acsl_add;
    __e_acsl_mpz_t __gen_e_acsl__3;
    int __gen_e_acsl_gt;
    __gmpz_init_set_si(__gen_e_acsl_n_2,(long)n);
    __gmpz_init(__gen_e_acsl_mul_2);
    __gmpz_mul(__gen_e_acsl_mul_2,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_2),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_2));
    __gmpz_init_set(__gen_e_acsl_u_2,
                    (__e_acsl_mpz_struct const *)(__gen_e_acsl_mul_2));
    __gmpz_init_set_si(__gen_e_acsl__2,1L);
    __gmpz_init(__gen_e_acsl_add);
    __gmpz_add(__gen_e_acsl_add,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_u_2),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__2));
    __gmpz_init_set(__gen_e_acsl_v,
                    (__e_acsl_mpz_struct const *)(__gen_e_acsl_add));
    __gmpz_init_set_si(__gen_e_acsl__3,0L);
    __gen_e_acsl_gt = __gmpz_cmp((__e_acsl_mpz_struct const *)(__gen_e_acsl_u_2),
                                 (__e_acsl_mpz_struct const *)(__gen_e_acsl__3));
    __e_acsl_assert(__gen_e_acsl_gt > 0,(char *)"Assertion",(char *)"main",
                    (char *)"\\let u = n * n;\n\\let v = u + 1; u > 0",9);
    __gmpz_clear(__gen_e_acsl_u_2);
    __gmpz_clear(__gen_e_acsl_n_2);
    __gmpz_clear(__gen_e_acsl_mul_2);
    __gmpz_clear(__gen_e_acsl_v);
    __gmpz_clear(__gen_e_acsl__2);
    __gmpz_clear(__gen_e_acsl_add);
    __gmpz_clear(__gen_e_acsl__3);
  }
  /*@ assert (\let u = 1; u) + 1 ≡ 2; */
  {
    int __gen_e_acsl_u_3;
    __e_acsl_mpz_t __gen_e_acsl_u_4;
    __e_acsl_mpz_t __gen_e_acsl__4;
    __e_acsl_mpz_t __gen_e_acsl_add_2;
    __e_acsl_mpz_t __gen_e_acsl__5;
    int __gen_e_acsl_eq;
    __gen_e_acsl_u_3 = 1;
    __gmpz_init_set_si(__gen_e_acsl_u_4,(long)__gen_e_acsl_u_3);
    __gmpz_init_set_si(__gen_e_acsl__4,1L);
    __gmpz_init(__gen_e_acsl_add_2);
    __gmpz_add(__gen_e_acsl_add_2,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_u_4),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__4));
    __gmpz_init_set_si(__gen_e_acsl__5,2L);
    __gen_e_acsl_eq = __gmpz_cmp((__e_acsl_mpz_struct const *)(__gen_e_acsl_add_2),
                                 (__e_acsl_mpz_struct const *)(__gen_e_acsl__5));
    __e_acsl_assert(__gen_e_acsl_eq == 0,(char *)"Assertion",(char *)"main",
                    (char *)"(\\let u = 1; u) + 1 == 2",12);
    __gmpz_clear(__gen_e_acsl_u_4);
    __gmpz_clear(__gen_e_acsl__4);
    __gmpz_clear(__gen_e_acsl_add_2);
    __gmpz_clear(__gen_e_acsl__5);
  }
  /*@ assert \let u = 1; (\let v = u + 1; v) ≡ 2; */
  {
    int __gen_e_acsl_u_5;
    __e_acsl_mpz_t __gen_e_acsl_v_2;
    __e_acsl_mpz_t __gen_e_acsl_u_6;
    __e_acsl_mpz_t __gen_e_acsl__6;
    __e_acsl_mpz_t __gen_e_acsl_add_3;
    __e_acsl_mpz_t __gen_e_acsl__7;
    int __gen_e_acsl_eq_2;
    __gen_e_acsl_u_5 = 1;
    __gmpz_init_set_si(__gen_e_acsl_u_6,(long)__gen_e_acsl_u_5);
    __gmpz_init_set_si(__gen_e_acsl__6,1L);
    __gmpz_init(__gen_e_acsl_add_3);
    __gmpz_add(__gen_e_acsl_add_3,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_u_6),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__6));
    __gmpz_init_set(__gen_e_acsl_v_2,
                    (__e_acsl_mpz_struct const *)(__gen_e_acsl_add_3));
    __gmpz_init_set_si(__gen_e_acsl__7,2L);
    __gen_e_acsl_eq_2 = __gmpz_cmp((__e_acsl_mpz_struct const *)(__gen_e_acsl_v_2),
                                   (__e_acsl_mpz_struct const *)(__gen_e_acsl__7));
    __e_acsl_assert(__gen_e_acsl_eq_2 == 0,(char *)"Assertion",
                    (char *)"main",
                    (char *)"\\let u = 1; (\\let v = u + 1; v) == 2",14);
    __gmpz_clear(__gen_e_acsl_v_2);
    __gmpz_clear(__gen_e_acsl_u_6);
    __gmpz_clear(__gen_e_acsl__6);
    __gmpz_clear(__gen_e_acsl_add_3);
    __gmpz_clear(__gen_e_acsl__7);
  }
  /*@ assert \let u = 1; (\let u = u + 1; u) ≡ 2; */
  {
    int __gen_e_acsl_u_7;
    __e_acsl_mpz_t __gen_e_acsl_u_8;
    __e_acsl_mpz_t __gen_e_acsl_u_9;
    __e_acsl_mpz_t __gen_e_acsl__8;
    __e_acsl_mpz_t __gen_e_acsl_add_4;
    __e_acsl_mpz_t __gen_e_acsl__9;
    int __gen_e_acsl_eq_3;
    __gen_e_acsl_u_7 = 1;
    __gmpz_init_set_si(__gen_e_acsl_u_9,(long)__gen_e_acsl_u_7);
    __gmpz_init_set_si(__gen_e_acsl__8,1L);
    __gmpz_init(__gen_e_acsl_add_4);
    __gmpz_add(__gen_e_acsl_add_4,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_u_9),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__8));
    __gmpz_init_set(__gen_e_acsl_u_8,
                    (__e_acsl_mpz_struct const *)(__gen_e_acsl_add_4));
    __gmpz_init_set_si(__gen_e_acsl__9,2L);
    __gen_e_acsl_eq_3 = __gmpz_cmp((__e_acsl_mpz_struct const *)(__gen_e_acsl_u_8),
                                   (__e_acsl_mpz_struct const *)(__gen_e_acsl__9));
    __e_acsl_assert(__gen_e_acsl_eq_3 == 0,(char *)"Assertion",
                    (char *)"main",
                    (char *)"\\let u = 1; (\\let u = u + 1; u) == 2",17);
    __gmpz_clear(__gen_e_acsl_u_8);
    __gmpz_clear(__gen_e_acsl_u_9);
    __gmpz_clear(__gen_e_acsl__8);
    __gmpz_clear(__gen_e_acsl_add_4);
    __gmpz_clear(__gen_e_acsl__9);
  }
  long m = 0x7fffffffffffffffL;
  /*@ assert (\let u = m; u * u) > m; */
  {
    long __gen_e_acsl_u_10;
    __e_acsl_mpz_t __gen_e_acsl_u_11;
    __e_acsl_mpz_t __gen_e_acsl_mul_3;
    __e_acsl_mpz_t __gen_e_acsl_m;
    int __gen_e_acsl_gt_2;
    __gen_e_acsl_u_10 = m;
    __gmpz_init_set_si(__gen_e_acsl_u_11,__gen_e_acsl_u_10);
    __gmpz_init(__gen_e_acsl_mul_3);
    __gmpz_mul(__gen_e_acsl_mul_3,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_u_11),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_u_11));
    __gmpz_init_set_si(__gen_e_acsl_m,m);
    __gen_e_acsl_gt_2 = __gmpz_cmp((__e_acsl_mpz_struct const *)(__gen_e_acsl_mul_3),
                                   (__e_acsl_mpz_struct const *)(__gen_e_acsl_m));
    __e_acsl_assert(__gen_e_acsl_gt_2 > 0,(char *)"Assertion",(char *)"main",
                    (char *)"(\\let u = m; u * u) > m",21);
    __gmpz_clear(__gen_e_acsl_u_11);
    __gmpz_clear(__gen_e_acsl_mul_3);
    __gmpz_clear(__gen_e_acsl_m);
  }
  char c = (char)'a';
  /*@ assert \let u = 'b'; c < u; */
  {
    int __gen_e_acsl_u_12;
    __e_acsl_mpz_t __gen_e_acsl_c;
    __e_acsl_mpz_t __gen_e_acsl_u_13;
    int __gen_e_acsl_lt;
    __gen_e_acsl_u_12 = 'b';
    __gmpz_init_set_si(__gen_e_acsl_c,(long)c);
    __gmpz_init_set_si(__gen_e_acsl_u_13,(long)__gen_e_acsl_u_12);
    __gen_e_acsl_lt = __gmpz_cmp((__e_acsl_mpz_struct const *)(__gen_e_acsl_c),
                                 (__e_acsl_mpz_struct const *)(__gen_e_acsl_u_13));
    __e_acsl_assert(__gen_e_acsl_lt < 0,(char *)"Assertion",(char *)"main",
                    (char *)"\\let u = \'b\'; c < u",24);
    __gmpz_clear(__gen_e_acsl_c);
    __gmpz_clear(__gen_e_acsl_u_13);
  }
  float f = 1.0f;
  __e_acsl_store_block((void *)(& f),(size_t)4);
  __e_acsl_full_init((void *)(& f));
  /*@ assert \let u = f; u ≡ f; */
  {
    float __gen_e_acsl_u_14;
    __gen_e_acsl_u_14 = f;
    __e_acsl_assert(__gen_e_acsl_u_14 == f,(char *)"Assertion",
                    (char *)"main",(char *)"\\let u = f; u == f",27);
  }
  int t[4] = {1, 2, 3, 4};
  /*@ assert \let u = &t[1]; 1 ≡ 1; */
  {
    int * /*[4]*/ __gen_e_acsl_u_15;
    __e_acsl_mpz_t __gen_e_acsl__10;
    int __gen_e_acsl_eq_4;
    __gen_e_acsl_u_15 = & t[1];
    __gmpz_init_set_si(__gen_e_acsl__10,1L);
    __gen_e_acsl_eq_4 = __gmpz_cmp((__e_acsl_mpz_struct const *)(__gen_e_acsl__10),
                                   (__e_acsl_mpz_struct const *)(__gen_e_acsl__10));
    __e_acsl_assert(__gen_e_acsl_eq_4 == 0,(char *)"Assertion",
                    (char *)"main",(char *)"\\let u = &t[1]; 1 == 1",30);
    __gmpz_clear(__gen_e_acsl__10);
  }
  /*@ assert (\let u = &t[1]; 1) ≡ 1; */
  {
    int * /*[4]*/ __gen_e_acsl_u_16;
    __gen_e_acsl_u_16 = & t[1];
    __e_acsl_assert(1,(char *)"Assertion",(char *)"main",
                    (char *)"(\\let u = &t[1]; 1) == 1",32);
  }
  struct __anonstruct_r_1 r = {.x = 1, .y = 2};
  __e_acsl_store_block((void *)(& r),(size_t)8);
  __e_acsl_full_init((void *)(& r));
  /*@ assert \let u = r; u.x + u.y ≡ 3; */
  {
    struct __anonstruct_r_1 __gen_e_acsl_u_17;
    __e_acsl_mpz_t __gen_e_acsl__11;
    __e_acsl_mpz_t __gen_e_acsl__12;
    __e_acsl_mpz_t __gen_e_acsl_add_5;
    __e_acsl_mpz_t __gen_e_acsl__13;
    int __gen_e_acsl_eq_5;
    __gen_e_acsl_u_17 = r;
    __gmpz_init_set_si(__gen_e_acsl__11,(long)__gen_e_acsl_u_17.x);
    __gmpz_init_set_si(__gen_e_acsl__12,(long)__gen_e_acsl_u_17.y);
    __gmpz_init(__gen_e_acsl_add_5);
    __gmpz_add(__gen_e_acsl_add_5,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__11),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__12));
    __gmpz_init_set_si(__gen_e_acsl__13,3L);
    __gen_e_acsl_eq_5 = __gmpz_cmp((__e_acsl_mpz_struct const *)(__gen_e_acsl_add_5),
                                   (__e_acsl_mpz_struct const *)(__gen_e_acsl__13));
    __e_acsl_assert(__gen_e_acsl_eq_5 == 0,(char *)"Assertion",
                    (char *)"main",(char *)"\\let u = r; u.x + u.y == 3",35);
    __gmpz_clear(__gen_e_acsl__11);
    __gmpz_clear(__gen_e_acsl__12);
    __gmpz_clear(__gen_e_acsl_add_5);
    __gmpz_clear(__gen_e_acsl__13);
  }
  s.x = 5;
  /*@ assert (\let u = s; u.x) > 0; */
  {
    union __anonunion_s_2 __gen_e_acsl_u_18;
    __gen_e_acsl_u_18 = s;
    __e_acsl_assert(__gen_e_acsl_u_18.x > 0,(char *)"Assertion",
                    (char *)"main",(char *)"(\\let u = s; u.x) > 0",39);
  }
  __retres = 0;
  __e_acsl_delete_block((void *)(& r));
  __e_acsl_delete_block((void *)(& f));
  __e_acsl_memory_clean();
  return __retres;
}


