(* This file was originally generated by why.
   It can be modified; only the generated parts will be overwritten. *)

Require Export Why.


Proof.
Admitted.

Proof.
Admitted.

Proof.
Admitted.

Proof.
Admitted.

Proof.
Admitted.

Proof.
Admitted.

Proof.
intuition.
unfold sorted_array.
simplify.

Proof.
intuition.
(* FILL PROOF HERE *)
Save.

Proof.
intuition.
(* FILL PROOF HERE *)
Save.

